# Generated by Django 3.2.6 on 2021-09-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
