# Generated by Django 3.2.6 on 2021-09-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_post_coins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='coins',
        ),
        migrations.AddField(
            model_name='profile',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
